name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installation Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma et des fichiers d'exemples
      run: |
        frictionless validate --type schema schema.json
        frictionless validate --schema schema.json exemples/exemple-valide.csv
        frictionless validate --schema schema.json exemples/exemple-valide.xlsx
        frictionless validate --schema schema.json exemples/exemple-valide.ods
